[package]
name = "sub-snap"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = "7.0"
opencv = { version = "0.94.4", features = ["clang-runtime"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
anyhow = "1.0"